name: envtest
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "TZ=Asia/Tokyo" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $TZ
          echo ${{ env.TZ }}
