name: Auto create issue
on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Get the title, labels, assignees, and body of the issue template at the path,
    # .github/ISSUE_TEMPLATE/my_template.md, if available.
    - uses: imjohnbo/extract-issue-template-fields@v1
      id: extract
      with:
        path: .github/ISSUE_TEMPLATE/auto_create_issue_test.md

    # Create new issue with assignees, labels, title, and body
    - uses: imjohnbo/issue-bot@v3
      with:        
        assignees: "masa06033"
        labels: ${{ steps.extract.outputs.body }}
        title:  チェック用issue
        body: ${{ steps.extract.outputs.body }}
        pinned: false
        close-previous: false
        linked-comments: false
        
        
