name: Auto create issue
on:
  schedule:
    - cron:  '*/15 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Get the title, labels, assignees, and body of the issue template at the path,
    # .github/ISSUE_TEMPLATE/my_template.md, if available.
    - uses: imjohnbo/extract-issue-template-fields@v1
      id: extract
      with:
        path: .github/ISSUE_TEMPLATE/auto_create_issue_test.md

    # Log outputs of previous step
    - run: |-
        echo $ASSIGNEES $LABELS $TITLE $BODY
      env:
        ASSIGNEES: ${{ steps.extract.outputs.assignees }}
        LABELS: ${{ steps.extract.outputs.labels }}
        TITLE: ${{ steps.extract.outputs.title }}
        BODY: ${{ steps.extract.outputs.body }}
        
    # Create new issue with assignees, labels, title, and body
    - uses: imjohnbo/issue-bot@v3
      with:
        assignees: ${{ steps.extract.outputs.assignees }}
        labels: ${{ steps.extract.outputs.labels }}
        title: ${{ steps.extract.outputs.title }}
        body: ${{ steps.extract.outputs.body }}
